### ISSUE TITLE
Add http request metrics

### ISSUE THREAD

**Issue by cmerrick** [singer-io/tap-zendesk#25]
Instrument every HTTP request to the Zendesk API to emit metrics about timing and success/failure.

Wrap all API calls with a [`singer.metrics.http_request_timer`](https://github.com/singer-io/singer-python/blob/master/singer/metrics.py#L210)

That should include at least these calls:
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L126
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L138
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L150
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L161
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L197
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L274
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L285
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L295
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L308
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L325
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L342
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L359
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L371
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L388
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L405
 - https://github.com/singer-io/tap-zendesk/blob/master/tap_zendesk/streams.py#L428

Verify behavior by ensuring that existing tests pass and METRICS messages are emitted in the expects places.

**Comment by aiguofer** [comment]
Since this is quite a few places to add, and any new streams will have to remember to add, I'm wondering if it might make sense to monkey patch the library [where it calls the API](https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L237)? 

I'm not generally a fan of monkey patching, especially on a non-public function, but adding the metric wrapper in so many places and having to remember to add them for any new streams seems harder to maintain than the monkey patch (especially since versions are pinned and the recommended deployment for the tap is using its own virtualenv).

Thoughts?

**Comment by cmerrick** [comment]
Ugh, yeah, it looks like even the `_query_zendesk` method has a cache inside it, so the only way to get accurate metrics is going to be to override the `_call_api` method. That's unfortunate, but I guess that's the price we pay for using the SDK.

**Comment by dmosorast** [comment]
For reliability, it might be worth it to patch `requests` instead, since its API is likely more stable.

**Comment by aiguofer** [comment]
Hmm I guess it depends on what the goal of tracking the time is. It looks like [`_call_api`](https://github.com/facetoe/zenpy/blob/master/zenpy/lib/api.py#L118) has some built in delays and retries for when they hit the API rate limit. I imagine that would be important to capture but we wouldn't get that from patching `requests`.

Similarly, if the call uses the cache, then `_call_api` won't get called, but wouldn't it still be useful to track how long it took?

**Comment by cmerrick** [comment]
We'd actually like to get as close to the HTTP call as possible, so patching requests does sound like a better move. The primary use case is understanding availability of the API (returning 500s versus 200s). Speed is interesting, but it's rarely actionable.

**Comment by aiguofer** [comment]
Cool yeah that makes sense. Looking at `requests`, it looks like `requests.request` is internally calling `Session.request` so I went ahead and patched that.
