### ISSUE TITLE
Zendesk API Limit Change

### ISSUE THREAD

**Issue by will-peloton** [singer-io/tap-zendesk#52]
Hello we use stitch and the zendesk integration is enabled by this. Just wanna double check Zendesk API Limit Change is already accounted for since the cutoff is 12/31/2020. I did quick search of recent commits and did not see related.
https://develop.zendesk.com/hc/en-us/articles/360022563994--BREAKING-New-Search-API-Result-Limits

**Comment by dmosorast** [comment]
Hi @will-peloton, yes, the tap will be able to handle the limit change. The only stream that is using the `search` API is `users`, and it has been modified to adjust the requested date range if more than 1000 results are returned. This uses the `count` value in the response as suggested in that article.

[Here](https://github.com/singer-io/tap-zendesk/blob/db707dab53e9084e7165a9768723be412e37e270/tap_zendesk/streams.py#L184-L189) is the relevant code.

**Comment by will-peloton** [comment]
@dmosorast thank you so much for the prompt reply! I will close this issue.
